# Default configuration

# Quiet output
quiet = false
# Verbose output
verbose = false
# Debug settings
debug = false
# Number of threads to use
threads = 1
# RNG seed
seed = 42
# Write token to debug log file (possible security implications)
log_token = false

[web]
# URL to Digestiflow Web UI API
url = ""
# API key token to use
token = ""

[ingest]
# The UUID of the project to import into by default
project_uuid = ""
# Path to flowcell to ingest
path = ""
# Whether or not to register flow cell
register = true
# Whether or not to update flow cell metadata
update = true
# Whether or not to read adapter information
analyze_adapters = false
# Whether or not to post adapter information (when read) to API
post_adapters = true
# The operator string to use.
operator = ""
# From how many tiles to sample (if there are tiles)
sample_tiles = 1
# How many reads to sample per tile (if there are files per tile)
sample_reads_per_tile = 0
